Added rough schema changes from reviews in past branch , main as sour…
shy-tan/humble-kanban pull request #6
Opened 2022-09-21 03:10 UTC by Angrypenguin1995

Made changes by adding status code etc for api specification. I know its far from good enough but maybe you guys can give me more inputs on what other changes might be needed to make it better? and in usermodel i though taking it phone number might be good but we can keep it very optional now. let me know whether its really needed.

2022-09-22 16:08 UTC, szjanecki requested changes

2022-09-22 16:08 UTC, szjanecki commented on docs/change_password.md
> +content_type : "application/json",
I think by default it is implied, we will mostly have application/json responses, no need to include that imo

2022-09-22 16:08 UTC, szjanecki commented on docs/change_password.md
> +        access_token: refreshed_access_token
Do we need that? If we are going to use expiration sliding, we'll include that in some header, not response. But I'm not sure if we should also. 

Expiration sliding is nice for internal apps for some companies, because it is useful to log out all employees at the end of the day, but in commercial apps as you see, usually you are logged for much longer, days possibly, so in such case there is no point in expiration sliding IMO

2022-09-24 03:50 UTC, Angrypenguin1995 commented on docs/login_specification.md
> +POST auth/login/
rename module to user? which module?

2022-09-24 03:58 UTC, Angrypenguin1995 commented on docs/register_specification.md
> +            #user created successfully
sorry its not a header , its just my bad habit of using # for comment in python acting as a header in markdown file. :smiley:

2022-09-24 04:32 UTC, Angrypenguin1995 commented on docs/change_password.md
> +        access_token: refreshed_access_token
well i removed it for now but maybe down the line we can add it if necessary.

2022-09-24 08:12 UTC, szjanecki commented on .gitignore
> +.vscode
Be careful about that. There are files that we want to share in there. I'm talking about these ones:
```
!source/client-app/.vscode/settings.json
!source/client-app/.vscode/tasks.json
!source/client-app/.vscode/launch.json
!source/client-app/.vscode/extensions.json
```

make sure they are still there

2022-09-24 08:12 UTC, szjanecki commented on docs/change_password.md
> +                token : bearer <jwt>,
Token goes in header `Authorization: "Bearer <jwt>"`. The other go in request body

2022-09-24 08:12 UTC, szjanecki commented on docs/change_password.md
> +        success response data
You could do these as h3 (###)

2022-09-24 12:59 UTC, Angrypenguin1995 commented on .gitignore
> +.vscode
so we want to have some files from settings.json ?

2022-09-24 13:10 UTC, Angrypenguin1995 commented on .gitignore
> +.vscode
I just removed it for now, but we can add them if we need something excluded later.

2022-09-24 13:14 UTC, Angrypenguin1995 commented on docs/change_password.md
> +        success response data
done this on all 3 files

2022-09-24 17:59 UTC, szjanecki approved these changes

2022-09-25 07:05 UTC, shy-tan commented on .gitignore
> +.vscode
Yes, the files from `.vscode` can be used to define a debugging workflow, or linting for example so they should not be ignored so we have a coherent config system.

2022-09-25 07:07 UTC, shy-tan approved these changes

2022-09-25 09:17 UTC, merged